import type { Metadata } from 'next';
import AllProviders from '@/providers';
import { Inter } from 'next/font/google';
import "./globals.css";
import Header from '@/components/Header';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "co voyage",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
	return (
		<html lang="en">
			<body>
				<AllProviders>
					<Header />
					{children}
				</AllProviders>
			</body>
		</html>
	);
}
